### ISSUE TITLE
Solidity helper function for randomness

### ISSUE THREAD

**Issue by fijter** [iotaledger/wasp-legacy#2747]
When using our magic smart contract entropy functionality you get a single deterministic random hash per block (only available after consensus has been reached, so unpredictable beforehand). If you wish to use this entropy for multiple random numbers you need to generate these random numbers based on this entropy (similar to https://www.geeksforgeeks.org/random-number-generator-in-solidity-using-keccak256/ but using the entropy from the magic contract instead of some other entropy source). It would be nice if we can offer some helper functionality here for some common use-cases to more easily generate random numbers/hashes without having to implement the functionality for converting entropy  + index to an actual list of random numbers/hashes. 
```[tasklist]
### Tasks
- [x] Helper function for generating a random uint256
- [x] Helper function for generating a random number within a certain range (min, max)
- [x] Helper function for generating a random hash (bytes32)
- [x] Documentation / examples in Wiki
```
